[package]
name = "nix-du"
version = "0.1.2"
authors = ["Symphorien Gibol <symphorien+git@xlumurb.eu>"]
license = "LGPL-3.0"

# otherwise we get an unhelpful panic unwind when a c++ execption is raised.
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[build-dependencies]
cc = "1.0"

[dependencies]
petgraph = "0.4"
fixedbitset = "0.1"
memchr = "2"
# output
humansize = "1"
# input
human-size = "0.3"
palette = "0.2"

[dependencies.clap]
version = "2"
features = ["suggestions", "color", "wrap_help"]

[dev-dependencies]
rand = "0.4"
cli_test_dir = "0.1"
regex = "0.2"
